version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: lavanya
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lavanya_db
    networks:
      - mynetwork

  app:
    build: .
    container_name: my-python-app
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
